#!/bin/bash
#this script illustrates the use of menu widget

temp1=$(mktemp -t test1.XXX)
temp2=$(mktemp -t test2.XXX)

function diskspace
#this function contains the commands to display the diskspace
{
  df -k > $temp1
  dialog --textbox $temp1 20 40
}

function whoseon
#this function contains the commands to display the users logged on
{
 who > $temp1
 dialog --textbox $temp1 20 40
}

function memusage
#this function contains the command to view the memory information
{
  cat /proc/meminfo > $temp1
  dialog --textbox $temp1 20 40
}

while [ 1 ] 
do 
dialog --menu " Menu" 20 30 10 1 "Display disk space" 2 "Display users" 3 "Display memory usage" 0 \
"Exit" 2> $temp2 
if [ $? -eq 1 ] 
then    
 break 
fi
 selection=$(cat $temp2)
 case $selection in 
1)    
diskspace 
;; 
2)    
whoseon 
;; 
3)    
memusage 
;; 
0)    
break 
;; 
*)    
dialog --msgbox "Sorry, invalid selection" 10 30
esac 
done 
rm -f $temp1 2> /dev/null 
rm -f $temp2 2> /dev/null 


